#!/bin/bash

DEPLOY_LOG="./deploy.log"
DATE=`date +"[%Y-%m-%d %H:%M:%S]"`
DEPOLY_FILE="cicd-test-0.0.1-SNAPSHOT.jar"

#jar 시작
sudo nohup java -jar ~/src/deploy/build/libs/$DEPOLY_FILE &
echo "$DATE : TOMCAT을 시작합니다." >> $DEPLOY_LOG
echo "###################################################" >> $DEPLOY_LOG
